CREATE TABLE user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login_id        VARCHAR(50) NOT NULL UNIQUE,
    password        VARCHAR(100) NOT NULL,
    name            VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
);
